[Rainmeter]
Update=1000
Author=HipHopium aka Connect-R

[Variables]
DayColor1=255,140,0,150
DayColor2=255,255,255
DayColor3=255,140,0

NightColor1=54,100,255,255
NightColor2=255,255,255
NightColor3=54,100,255

@include=#@#Variables.inc

;-------------------------------------------------------------
;-------------------------------------------------------------

[Background]
Meter=image
W=360
H=360
SolidColor=0,0,0,0

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeasureDay]
Measure=Time
Format=%A
Substitute=#Date#

[MeasureMonth]
Measure=Time
Format=%d, %B
Substitute=#Date#

[MeasureTime]
Measure=Time

[MeasureTimeCalc]
Measure=Calc
Formula=Trunc((MeasureTime % (60 * 60 * 24)) / (60 * 60))
IfCondition=(MeasureTimeCalc <= 12)
IfTrueAction=[!SetOption MeterDay InlineSetting "Shadow | 6 | 4 | 2 | #DayColor1#"][!SetOption MeterDay InlineSetting2 "Shadow | 0 | 0 | 5.5 | #DayColor2#"]
IfFalseAction=[!SetOption MeterDay InlineSetting "Shadow | 6 | 4 | 2 | #NightColor1#"][!SetOption MeterDay InlineSetting2 "Shadow | 0 | 0 | 5.5 | #NightColor2#"]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterDay]
Meter=String
MeasureName=MeasureDay
StringAlign=Center
FontColor=255,255,255,220
FontFace=Signerica Medium
FontSize=52
TransformationMatrix=0.8;0;0;1.0;0;0
X=600
Y=240
W=600
Text=%1
AntiAlias=1
InlineSetting=Shadow | 6 | 4 | 2 | #NightColor1#
InlineSetting2=Shadow | 0 | 0 | 5.5 | #NightColor2#
InlineSetting3=Shadow | 0 | 0 | 9.9 | 255,255,255
DynamicVariables=1

[MeterMonth]
Meter=String
MeasureName=MeasureMonth
StringStyle=Bold
StringCase=Upper
StringAlign=Center
FontColor=255,255,255,200
FontFace=Harry Thin
FontWeight=950
FontSize=20
X=490
Y=355
Text=%1
AntiAlias=1
